name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Maven Verify
        run: mvn -B clean test
